import type { Metadata } from "next";
import { JetBrains_Mono, Oswald, Sora } from "next/font/google";
import { ScrollProvider } from "../components/layout/ScrollProvider";
import "./globals.css";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${sora.variable} ${oswald.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
